# Generated by Django 5.0.6 on 2024-08-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_card',
            options={'verbose_name_plural': 'Product_Cards'},
        ),
    ]
