# Generated by Django 5.0.6 on 2024-08-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0003_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
