# Generated by Django 5.1 on 2024-08-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0004_remove_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='carousel_slide')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Carousel_Slide',
            },
        ),
    ]
