# Generated by Django 5.1.1 on 2024-10-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0005_carousel_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel_Slide',
        ),
    ]
